name: Deploy Globetrotter changes to cPanel

on:
  push:
    branches:
      - starter
      - main

jobs:
  deploy:
    name: FTP deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@master
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: src
        REMOTE_DIR: staging
        ARGS: --delete --verbose
